/* Generated by Together */

package bj.DesignPattern.JavaAndPattern.COMMAND.television;

public interface Invoker {

	void invoke();

	/**
	 * @link aggregation
	 * @directed
	 */
	/*#Command lnkCommand;*/

}
