SELECT * FROM CUSTOMER;
SELECT * FROM STOCK;
SELECT * FROM ITEMS ;
select * from purchase ;

INSERT INTO PURCHASE VALUES(9001,TO_CHAR(1,'0000'),'12-4月-1998','7-6月-1998','李一',1234);
INSERT INTO ITEMS VALUES(1001,9001,1001,5,0.2);
--1．查询订单号为9001订单的客户信息和订货详细信息。
 SELECT P.PID,  C.CID, C.CNAME, C.CADDR, C.CPOST, C.CTEL, I.SID ,S.SNAME,S.SPRICE,I.DISCOUNT , I.SNUM , (S.SPRICE * I.SNUM *  I.DISCOUNT) "总价"
   FROM PURCHASE P, CUSTOMER C, ITEMS I ,STOCK S
  WHERE P.CID = C.CID
    AND P.PID = I.PID
    AND I.SID =  S.SID
    AND P.PID = 9001;
 
--2．查询每张订单的订货详细信息
 SELECT P.*,       
        C.CNAME,
        C.CADDR,
        C.CPOST,
        C.CTEL,
        I.SID,
        S.SNAME,
        S.SPRICE,
        I.DISCOUNT,
        I.SNUM,
        (S.SPRICE * I.SNUM * I.DISCOUNT) "总价"
   FROM PURCHASE P, CUSTOMER C, ITEMS I, STOCK S
  WHERE P.CID = C.CID
    AND P.PID = I.PID
    AND I.SID = S.SID;
 
 --3．统计每一个订货单的总价值
SELECT I.PID, S.SPRICE*I.SNUM*(I.DISCOUNT) "总价格"
FROM ITEMS I,STOCK S
WHERE I.SID=S.SID;



--4．查询涉及货物1003的订货单及订货条目信息
SELECT I.PID,I.IID
FROM ITEMS I,STOCK S
WHERE I.SID=S.SID AND I.SID=1003;

--5．更改1001订货单中货物为1003的订货量
UPDATE ITEMS I SET I.SNUM=6 WHERE I.SID=1003 ;
COMMIT;
SELECT * FROM ITEMS;


--6．删除编号为9001的订货单
DELETE FROM ITEMS WHERE PID=9001;
DELETE FROM PURCHASE WHERE PID=9001;
COMMIT;

