/* Generated by Together */

package bj.DesignPattern.JavaAndPattern.COMMAND.drawapplet;

public interface Command {

	abstract public void execute();

	abstract public void unexecute();

	abstract public boolean canExecute();

	abstract public boolean canUnexecute();

}

