/* Generated by Together */

package bj.DesignPattern.JavaAndPattern.composite.filesystem;

public class FileNode extends FileSystemNode {

	public FileNode() {
	}

	public int getSize() {
		return 0;
	}

}
