/* Generated by Together */

package bj.DesignPattern.JavaAndPattern.FACADE.sessionfacade;

import javax.ejb.CreateException;
import javax.ejb.EJBException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

public interface Business2Home extends EJBHome {

	Business2 create() throws CreateException, EJBException, RemoteException;

	/** @link dependency */
	/*#Business1Bean lnkSession1Bean;*/
}
