/* Generated by Together */

package bj.DesignPattern.JavaAndPattern.FACADE.sessionfacade;

public class Client {

	/**
	 * @label Uses
	 * @directed
	 */
	private SessionFacadeBean lnkSessionFacadeBean;
}
