/* Generated by Together */

package bj.DesignPattern.JavaAndPattern.FACADE.sessionfacade;

import javax.ejb.EJBException;
import javax.ejb.EJBObject;
import java.rmi.RemoteException;

public interface SessionFacade extends EJBObject {

	void BusinessMethod2() throws RemoteException, EJBException;

	void BusinessMethod1() throws RemoteException, EJBException;

	/** @link dependency */
	/*#SessionFacadeBean lnkSession1Bean;*/
}
