/* Generated by Together */

package bj.DesignPattern.JavaAndPattern.MEMENTO.wideandnarrow1;

public class User {
	/** @link dependency */
	/*#Wide lnkWide;*/

	/** @link dependency */
	/*#ConcreteClass lnkConcreteClass;*/
}
