/* Generated by Together */

package bj.DesignPattern.JavaAndPattern.ISP.altavista;

public class RdbIndexer implements Indexer {

	public void reIndexAll() {
		//write your code here
	}

	public void updateIndex() {
		//write your code here
	}

}
