/* Generated by Together */

package bj.DesignPattern.JavaAndPattern.STATE.drawingtool;

public class TextTool implements Tool {

	public void handleMousePress() {
	}

	public void handleMouseRelease() {
	}

	public void handleCharacter() {
	}

	public void getCursor() {
	}

	public void activate() {
	}

}
