/* Generated by Together */

package bj.DesignPattern.JavaAndPattern.STATE.drawingtool;

public interface Tool {

	void handleMousePress();

	void handleMouseRelease();

	void handleCharacter();

	void getCursor();

	void activate();

	/**
	 * @link
	 * @shapeType PatternLink
	 * @pattern State*/
	/*# private DrawingController _drawingController; */

}
